
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


//namespace ??????
//{

//    using System;
//    using System.Collections.Generic;

//    public partial class ADVERTISEMENT
//    {

//        public int ADV_ID { get; set; }

//        public string IMAGE_SOURCE { get; set; }

//        public string LINK { get; set; }

//    }

//}
