
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Курсач
{

using System;
    using System.Collections.Generic;
    
public partial class BOOKS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BOOKS()
    {

        this.BASKETS = new HashSet<BASKETS>();

        this.YOUR_BOOKS = new HashSet<YOUR_BOOKS>();

        this.MARKS = new HashSet<MARKS>();

    }


    public int BOOK_ID { get; set; }

    public string TITLE { get; set; }

    public string AUTHOR { get; set; }

    public Nullable<int> GENRE { get; set; }

    public decimal PRICE { get; set; }

    public string COVER { get; set; }

    public string CATEGORY { get; set; }

    public decimal RATING { get; set; }

    public string DESCRIPTION { get; set; }

    public string LINK { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BASKETS> BASKETS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<YOUR_BOOKS> YOUR_BOOKS { get; set; }

    public virtual GENRES GENRES { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MARKS> MARKS { get; set; }

}

}
