

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Курсач
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class LIBRARYEntities : DbContext
{
    public LIBRARYEntities()
        : base("name=LIBRARYEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    //public virtual DbSet<ADVERTISEMENT> ADVERTISEMENT { get; set; }

    public virtual DbSet<BASKETS> BASKETS { get; set; }

    public virtual DbSet<BOOKS> BOOKS { get; set; }

    public virtual DbSet<GENRES> GENRES { get; set; }

    public virtual DbSet<MARKS> MARKS { get; set; }

    public virtual DbSet<SUBSCRIPTIONS> SUBSCRIPTIONS { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<USERS> USERS { get; set; }

    public virtual DbSet<YOUR_BOOKS> YOUR_BOOKS { get; set; }

}

}

