
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Курсач
{

using System;
    using System.Collections.Generic;
    
public partial class SUBSCRIPTIONS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SUBSCRIPTIONS()
    {

        this.USERS = new HashSet<USERS>();

    }


    public int SUBSCRIPTION_ID { get; set; }

    public System.DateTime SUBSCRIPTION_DATE { get; set; }

    public Nullable<int> LENGTH { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<USERS> USERS { get; set; }

}

}
